

export const quranList = [
  // =========================
  // MALE RECITERS 
  // =========================
  { id: 1, background:'bg-green-900', image: "A", name: "Ahmad Neinaa", gender: "male", link:"https://qurancentral.com/audio/ahmed-neinaa" },
  { id: 2, background:'bg-blue-900', image: "I", name: "Idriss Abkar", gender: "male", link:"https://qurancentral.com/audio/idriss-abkar" },
  { id: 3, background:'bg-gray-900', image: "M", name: "Mohammad Ayyub Asif", gender: "male", link:"https://qurancentral.com/audio/mohammad-ayyub-asif" },
  { id: 4, background:'bg-red-900', image: "A", name: "Abdul Basit Mujawwad", gender: "male", link: "https://qurancentral.com/audio/abdul-basit-mujawwad" },
  { id: 5, background:'bg-yellow-900', image: "A", name: "Abdur Rahman As-Sudais", gender: "male", link:"https://qurancentral.com/audio/abdur-rahman-as-sudais" },
  { id: 6, image: "A", background:'bg-black', name: "Abu Bakr al-Shatri", gender: "male", link:"https://qurancentral.com/audio/abu-bakr-al-shatri" },
  { id: 7, image: "F", background:'bg-pink-900', name: "Fatih Seferagic", gender: "male", link:"https://qurancentral.com/audio/fatih-seferagic" },
  { id: 8, image: "M", background:'bg-green-900', name: "Maher Al Mueaqly", gender: "male", link:"https://qurancentral.com/audio/maher-al-mueaqly" },
  { id: 9, image: "M", background:'bg-blue-900', name: "Mahmoud Khalil Al-Husary", gender: "male", link:"https://qurancentral.com/audio/mahmoud-khalil-al-husary" },
  { id: 10, image: "M", background:'bg-gray-900', name: "Mishary Rashid Alafasy", gender: "male", link:"https://qurancentral.com/audio/mishary-rashid-alafasy" },
  { id: 11, image: "R", background:'bg-red-900', name: "Raad Mohammad al Kurdi", gender: "male", link:"https://qurancentral.com/audio/raad-mohammad-al-kurdi" },
  { id: 12, image: "S", background:'bg-yellow-900', name: "Saad al-Ghamdi", gender: "male", link:"https://qurancentral.com/audio/saad-al-ghamdi" },
  { id: 13, image: "S", background:'bg-black', name: "Sahl Yasin", gender: "male", link:"https://qurancentral.com/audio/sahl-yasin" },
  { id: 14, image: "S", background:'bg-green-900', name: "Saud Al-Shuraim", gender: "male", link:"https://qurancentral.com/audio/saud-al-shuraim" },
  { id: 15, image: "Y", background:'bg-blue-900', name: "Yasser Al Dossari", gender: "male", link:"https://qurancentral.com/audio/yasser-al-dossari" },
  { id: 16, image: "Y", background:'bg-gray-900', name: "Yahya Ali", gender: "male", link:"https://qurancentral.com/audio/yahya-ali" },
  { id: 17, image: "M", background:'bg-red-900', name: "Muhammad Al-Muqatil Al-Ibrahimi - Warsh", gender: "male", link:"https://qurancentral.com/audio/muhammad-al-muqatil-al-ibrahimi-warsh" },
  { id: 18, image: "E", background:'bg-yellow-900', name: "Ezzat Rashed", gender: "male", link:"https://qurancentral.com/audio/ezzat-rashed" },
  { id: 19, image: "A", background:'bg-black', name: "Abu Taymiyyah", gender: "male", link:"https://qurancentral.com/audio/abu-taymiyyah" },
  { id: 20, image: "W", background:'bg-green-900', name: "Waseem Hendricks", gender: "male", link:"https://qurancentral.com/audio/waseem-hendricks" },
  { id: 21, image: "S", background:'bg-blue-900', name: "Saalim Peck", gender: "male", link:"https://qurancentral.com/audio/saalim-peck" },
  { id: 22, image: "A", background:'bg-pink-900', name: "Abdullah Forbes", gender: "male", link:"https://qurancentral.com/audio/abdullah-forbes" },
  { id: 23, image: "A", background:'bg-gray-900', name: "Abdallah Kamel", gender: "male", link:"https://qurancentral.com/audio/abdallah-kamel" },
  { id: 24, image: "A", background:'bg-red-900',name: "Abdel Aziz Al Ahmed", gender: "male", link:"https://qurancentral.com/audio/abdel-aziz-al-ahmed" },
  { id: 25, image: "A", background:'bg-yellow-900', name: "Abdul Rahman Al Yusuf", gender: "male", link:"https://qurancentral.com/audio/abdul-rahman-al-yusuf" },
  { id: 26, image: "A", background:'bg-pink-900', name: "Abdullah Al Matrood", gender: "male", link:"https://qurancentral.com/audio/abdullah-al-matrood" },
  { id: 27, image: "A", background:'bg-black',name: "Abdullahi Abba Zaria", gender: "male", link:"https://qurancentral.com/audio/abdullahi-abba-zaria" },
  { id: 28, image: "A", background:'bg-green-900', name: "Abdur Rasheed Sufi - [Khalaf]", gender: "male", link:"https://qurancentral.com/audio/abdu-rasheed-as-sufi" },
  { id: 29, image: "A", background:'bg-gray-900', name: "Afif Muhammad Taj", gender: "male", link:"https://qurancentral.com/audio/afif-muhammad-taj" },
  { id: 30, image: "A", background:'bg-red-900', name: "Ahmad Taleb Hameed", gender: "male", link:"https://qurancentral.com/audio/ahmad-taleb-hameed" },
  { id: 31, image: "A", background:'bg-blue-900', name: "Ali Abdur-Rahman al-Huthaify", gender: "male", link:"https://qurancentral.com/audio/ali-abdur-rahman-al-huthaify" },
  { id: 32, image: "A", background:'bg-yellow-900', name: "Ali Abu Hashem", gender: "male", link:"https://qurancentral.com/audio/ali-abu-hashem" },
  { id: 33, image: "A", background:'bg-pink-900', name: "Badr Al-Turki", gender: "male", link:"https://qurancentral.com/audio/badr-al-turki" },
  { id: 34, image: "M", background:'bg-green-900',name: "Mahmood Shahat", gender: "male", link:"https://qurancentral.com/audio/mahmood-shahat" },
  { id: 35, image: "M", background:'bg-black-900',name: "Maher Al Mueaqly", gender: "male", link:"https://qurancentral.com/audio/maher-al-mueaqly" },

  // =========================  
  // FEMALE RECITERS 
  // =========================
  { id: 23, image: "A", background:'bg-red-900', name: "Aisha Muhammad Auwal", gender: "female", link:"https://qurancentral.com/audio/aisha-muhammad-auwal" },
  { id: 24, image: "A", background:'bg-pink-900', name: "Asma Huda Zubair", gender: "female", link:"https://qurancentral.com/audio/asma-huda-zubair" },
  { id: 25, image: "A", background:'bg-green-900', name: "Assiatou Jallow", gender: "female", link:"https://qurancentral.com/audio/assiatou-jallow" },
  { id: 26, image: "A", background:'bg-blue-900', name: "Atiiqah Suhaimi", gender: "female", link:"https://qurancentral.com/audio/atiiqah-suhaimi" },
  { id: 27, image: "C", background:'bg-yellow-900', name: "Chaima Belmerabta", gender: "female", link:"https://qurancentral.com/audio/chaima-belmerabta" },
  { id: 28, image: "C", background:'bg-gray-900', name: "Chaimae Zaroual", gender: "female", link:"https://qurancentral.com/audio/chaimae-zaroual" },
  { id: 29, image: "C", background:'bg-pink-900', name: "Chaymae Belhadri", gender: "female", link:"https://qurancentral.com/audio/chaymae-belhadri" },
  { id: 30, image: "C", background:'bg-black', name: "Chaymae Yousfi", gender: "female", link:"https://qurancentral.com/audio/chaymae-yousfi" },
  { id: 31, image: "F", background:'bg-pink-900', name: "Farah Amchichou", gender: "female", link:"https://qurancentral.com/audio/farah-amchichou" },
  { id: 32, image: "F", background:'bg-red-900', name: "Farah El Bakkali", gender: "female", link:"https://qurancentral.com/audio/farah-el-bakkali" },
  { id: 33, image: "F", background:'bg-blue-900', name: "Farhatul Fairuzah", gender: "female", link:"https://qurancentral.com/audio/farhatul-fairuzah" },
  { id: 34, image: "F", background:'bg-gray-900', name: "Faridah Mat Saman", gender: "female", link:"https://qurancentral.com/audio/faridah-mat-saman" },
  { id: 35, image: "F", background:'bg-green-900', name: "Fatima Umar Harun", gender: "female", link:"https://qurancentral.com/audio/fatima-umar-harun" },
  { id: 36, image: "F", background:'bg-pink-900', name: "Fatima Zahrae Elmrabta", gender: "female", link:"https://qurancentral.com/audio/fatima-zahrae-elmrabta" },
  { id: 37, image: "H", background:'bg-yellow-900', name: "Hajar Boussaq", gender: "female", link:"https://qurancentral.com/audio/hajar-boussaq" },
  { id: 38, image: "H", background:'bg-blue-900', name: "Hajar Hniti", gender: "female", link:"https://qurancentral.com/audio/hajar-hniti" },
  { id: 39, image: "H", background:'bg-red-900', name: "Hajer Ben Saleh", gender: "female", link:"https://qurancentral.com/audio/hajer-ben-saleh" },
  { id: 40, image: "H", background:'bg-gray-900', name: "Hanan Fikri", gender: "female", link:"https://qurancentral.com/audio/hanan-fikri" },
  { id: 41, image: "J", background:'bg-black', name: "Jennifer Grout", gender: "female", link:"https://qurancentral.com/audio/jennifer-grout" },
  { id: 42, image: "K", background:'bg-yellow-900', name: "Khadija Azdad", gender: "female", link:"https://qurancentral.com/audio/khadija-azdad" },
  { id: 43, image: "M", background:'bg-yellow-900', name: "Maria Ulfah", gender: "female", link:"https://qurancentral.com/audio/maria-ulfah" },
  { id: 44, image: "M", background:'bg-blue-900', name: "Maryam Amir", gender: "female", link:"https://qurancentral.com/audio/maryam-amir" },
  { id: 45, image: "M", background:'bg-red-900', name: "Meriem Guerroumi", gender: "female", link:"https://qurancentral.com/audio/meriem-guerroumi" },
  { id: 46, image: "M", background:'bg-pink-900', name: "Muna Abdifatah Abdifarah", gender: "female", link:"https://qurancentral.com/audio/muna-abdifatah-abdifarah" },
  { id: 47, image: "N", background:'bg-gray-900', name: "Nor Azrah Ayub", gender: "female", link:"https://qurancentral.com/audio/nor-azrah-ayub" },
  { id: 48, image: "R", background:'bg-green-900', name: "Rahmas Abdullah", gender: "female", link:"https://qurancentral.com/audio/rahmas-abdullah" },
  { id: 49, image: "R", background:'bg-gray-900', name: "Rodziah Abdulrahman", gender: "female", link:"https://qurancentral.com/audio/rodziah-abdulrahman" },
  { id: 50, image: "R", background:'bg-black', name: "Rogayah Sulong", gender: "female", link:"https://qurancentral.com/audio/rogayah-sulong" },
  { id: 51, image: "R", background:'bg-pink-900', name: "Ruweyda Kassim Mohamed", gender: "female", link:"https://qurancentral.com/audio/ruweyda-kassim-mohamed" },
  { id: 52, image: "S", background:'bg-red-900', name: "Sabaha Salik", gender: "female", link:"https://qurancentral.com/audio/sabaha-salik" },
  { id: 53, image: "S", background:'bg-blue-900', name: "Safa Ghoulem", gender: "female", link:"https://qurancentral.com/audio/safa-ghoulem" },
  { id: 54, image: "S", background:'bg-green-900', name: "Sakina Hassan", gender: "female", link:"https://qurancentral.com/audio/sakina-hassan" },
  { id: 55, image: "S", background:'bg-blue-900', name: "Sharifah Khasif", gender: "female", link:"https://qurancentral.com/audio/sharifah-khasif" },
  { id: 56, image: "W", background:'bg-red-900', name: "Wardatun Nisa Hasan", gender: "female", link:"https://qurancentral.com/audio/wardatun-nisa-hasan" },
  { id: 57, image: "Z", background:'bg-pink-900', name: "Zainab Tanimu Zailani", gender: "female", link:"https://qurancentral.com/audio/zainab-tanimu-zailani" },
  { id: 58, image: "Z", background:'bg-yellow', name: "Zaynab Talha", gender: "female", link:"https://qurancentral.com/audio/zaynab-talha" },
  { id: 59, image: "Z", background:'bg-black', name: "Zeina Chewaf", gender: "female", link:"https://qurancentral.com/audio/zeina-chewaf" },
];

