

export const quranList = [
  // =========================
  // MALE RECITERS
  // =========================
  { id: 1, image: "A", name: "Ahmad Neinaa", gender: "male", link:"" },
  { id: 2, image: "M", name: "Mahmood Shahat", gender: "male", link:"" },
  { id: 3, image: "M", name: "Mohammad Ayyub Asif", gender: "male", link:"" },
  { id: 4, image: "A", name: "Abdul Basit Mujawwad", gender: "male", link: "https://qurancentral.com/audio/abdul-basit-mujawwad" },
  { id: 5, image: "A", name: "Abdur Rahman As-Sudais", gender: "male", link:"" },
  { id: 6, image: "A", name: "Abu Bakr al-Shatri", gender: "male", link:"" },
  { id: 7, image: "F", name: "Fatih Seferagic", gender: "male", link:"" },
  { id: 8, image: "M", name: "Maher Al Mueaqly", gender: "male", link:"" },
  { id: 9, image: "M", name: "Mahmoud Khalil Al-Husary", gender: "male", link:"" },
  { id: 10, image: "M", name: "Mishary Rashid Alafasy", gender: "male", link:"" },
  { id: 11, image: "R", name: "Raad Mohammad al Kurdi", gender: "male", link:"" },
  { id: 12, image: "S", name: "Saad al-Ghamdi", gender: "male", link:"" },
  { id: 13, image: "S", name: "Sahl Yasin", gender: "male", link:"" },
  { id: 14, image: "S", name: "Saud Al-Shuraim", gender: "male", link:"" },
  { id: 15, image: "Y", name: "Yasser Al Dossari", gender: "male", link:"https://qurancentral.com/audio/yasser-al-dossari" },
  { id: 16, image: "Y", name: "Yahya Ali", gender: "male", link:"" },
  { id: 17, image: "M", name: "Muhammad Al-Muqatil Al-Ibrahimi - Warsh", gender: "male", link:"" },
  { id: 18, image: "E", name: "Ezzat Rashed", gender: "male", link:"" },
  { id: 19, image: "A", name: "Abu Taymiyyah", gender: "male", link:"" },
  { id: 20, image: "W", name: "Waseem Hendricks", gender: "male", link:"" },
  { id: 21, image: "S", name: "Saalim Peck", gender: "male", link:"" },
  { id: 22, image: "A", name: "Abdullah Forbes", gender: "male", link:"" },

  // =========================
  // FEMALE RECITERS
  // =========================
  { id: 23, image: "A", name: "Aisha Muhammad Auwal", gender: "female", link:"" },
  { id: 24, image: "A", name: "Asma Huda Zubair", gender: "female", link:"" },
  { id: 25, image: "A", name: "Assiatou Jallow", gender: "female", link:"" },
  { id: 26, image: "A", name: "Atiiqah Suhaimi", gender: "female", link:"" },
  { id: 27, image: "C", name: "Chaima Belmerabta", gender: "female", link:"" },
  { id: 28, image: "C", name: "Chaimae Zaroual", gender: "female", link:"" },
  { id: 29, image: "C", name: "Chaymae Belhadri", gender: "female", link:"" },
  { id: 30, image: "C", name: "Chaymae Yousfi", gender: "female", link:"" },
  { id: 31, image: "F", name: "Farah Amchichou", gender: "female", link:"" },
  { id: 32, image: "F", name: "Farah El Bakkali", gender: "female", link:"" },
  { id: 33, image: "F", name: "Farhatul Fairuzah", gender: "female", link:"" },
  { id: 34, image: "F", name: "Faridah Mat Saman", gender: "female", link:"" },
  { id: 35, image: "F", name: "Fatima Umar Harun", gender: "female", link:"" },
  { id: 36, image: "F", name: "Fatima Zahrae Elmrabta", gender: "female", link:"" },
  { id: 37, image: "H", name: "Hajar Boussaq", gender: "female", link:"" },
  { id: 38, image: "H", name: "Hajar Hniti", gender: "female", link:"" },
  { id: 39, image: "H", name: "Hajer Ben Saleh", gender: "female", link:"" },
  { id: 40, image: "H", name: "Hanan Fikri", gender: "female", link:"" },
  { id: 41, image: "J", name: "Jennifer Grout", gender: "female", link:"" },
  { id: 42, image: "K", name: "Khadija Azdad", gender: "female", link:"" },
  { id: 43, image: "M", name: "Maria Ulfah", gender: "female", link:"" },
  { id: 44, image: "M", name: "Maryam Amir", gender: "female", link:"" },
  { id: 45, image: "M", name: "Meriem Guerroumi", gender: "female", link:"" },
  { id: 46, image: "M", name: "Muna Abdifatah Abdifarah", gender: "female", link:"" },
  { id: 47, image: "N", name: "Nor Azrah Ayub", gender: "female", link:"" },
  { id: 48, image: "R", name: "Rahmas Abdullah", gender: "female", link:"" },
  { id: 49, image: "R", name: "Rodziah Abdulrahman", gender: "female", link:"" },
  { id: 50, image: "R", name: "Rogayah Sulong", gender: "female", link:"" },
  { id: 51, image: "R", name: "Ruweyda Kassim Mohamed", gender: "female", link:"" },
  { id: 52, image: "S", name: "Sabaha Salik", gender: "female", link:"" },
  { id: 53, image: "S", name: "Safa Ghoulem", gender: "female", link:"" },
  { id: 54, image: "S", name: "Sakina Hassan", gender: "female", link:"" },
  { id: 55, image: "S", name: "Sharifah Khasif", gender: "female", link:"" },
  { id: 56, image: "W", name: "Wardatun Nisa Hasan", gender: "female", link:"" },
  { id: 57, image: "Z", name: "Zainab Tanimu Zailani", gender: "female", link:"" },
  { id: 58, image: "Z", name: "Zaynab Talha", gender: "female", link:"" },
  { id: 59, image: "Z", name: "Zeina Chewaf", gender: "female", link:"" },
];

